### ISSUE TITLE
How should we guide people in using this repository to address issues & questions?

### ISSUE THREAD

**Issue by ctb** [dcppc/data-stewards#10]
For example, for issue #6 (Pitfalls: Describe the situations in which others misinterpret or mis-parse your data), what is the suggested way to add details? Should we suggest that people "add to issue", or are we establishing a pull request for each that people add to and then review, or what?

My recommendation, based on about 5 minutes of thought:

* create an issue for each question/data-set combination (e.g. "TopMed, Pitfalls");
* ask people to braindump into the issue;
* at some point, delegate someone to summarize into a markdown document with associated PR
* circulate markdown/PR with request for comments
* after merge, repeat process with slightly more refined issue tracking;

cc @jmcmurry @owhite 

@luizirber on my team suggests that perhaps we can semi-automate the 'issues to markdown document' step by providing some scraping scripts.

**Comment by jmcmurry** [comment]
I don't think we need to overthink it. My suggestion for this issue would be to first start brain dumping in a google doc linked from the issue; it is much easier to comment and question line items in that venue. Once we've all iterated a few times, we can convert it to markdown and further refine in GitHub. Open to other suggestions.

**Comment by ctb** [comment]
Sounds good. Let me know if I can help in any way.

**Comment by jmcherry** [comment]
This is difficult because it is so open ended for MODs and Alliance. We have 20 years of help desk questions. How about we start with a couple of data types?

**Comment by ctb** [comment]
OK. I'll close this now that people seem to be brain dumping into & interacting around github issues!
