### ISSUE TITLE
Zones or regions for S3 buckets to store pilot datasets

### ISSUE THREAD

**Issue by sethi7ik** [dcppc/data-stewards#11]
What AWS and GCP zones or region will be used to store the data for the TOPMed and GTEx datasets?

**Comment by jmcherry** [comment]
The NIH staff can answer the question about AWS.  For the Alliance GCP account we are using us-west1 which is located in Oregon.

-Mike

**Comment by sethi7ik** [comment]
Thanks, Mike.

**Comment by francois-a** [comment]
GTEx on GCP is in US Multi-Regional buckets.

**Comment by jmcherry** [comment]
I think this issue has been answered. Closing.

**Comment by webermn** [comment]
Sorry to comment on a closed issue, but for AWS, all data sets are hosted by NHLBI and are in US-East-1.
