### ISSUE TITLE
Make Repo private?

### ISSUE THREAD

**Issue by bheavner** [dcppc/data-stewards#17]
Some responses we (the TOPMed data stewards) would like to contribute contain information we’re uncomfortable posting publicly in this open repo. Can we make this a private repository?

**Comment by bheavner** [comment]
@owhite - tagging you to draw your attention.

**Comment by avsmith** [comment]
2nd this idea. The proposal for a separate private repo should solve this, balancing the issues.

**Comment by jmcherry** [comment]
yes it would need to be another private repo.  There are so many Alliance people and we want people to be able to join at any time even for one ticket.  I would second something like data-stewards-private

**Comment by bheavner** [comment]
Heh. I guess this is revisiting Issue #8 which was closed pretty quickly, and before this circumstance came up. I don't think a separate private repo is necessary for my particular use case - I really just want to share the link to the TOPMed whitepaper, which is not for public distribution. There must be some other way to share that kind of internal document, right? The link is in the slack channel, for example, but it feels awkward to reference that document in issue comments in this repository without some sort of direct (access controlled) link.

More generally, if there are other issues that merit an (additional, private) repository, wouldn't jumping between issue comments across two repositories be a pretty awkward way to thread conversation? I'm not sure how the practical mechanics would work if there's a comment on an issue in the public data stewards repository, and I want to reply to it in an access controlled repository.

So perhaps I should amend the issue to requesting an access-controlled location for internal documentation that I can reference from this repository?

**Comment by ctb** [comment]
hi all, a few thoughts --

* it is more straightforward to set up a private repo now, and many (not yet all) will have access via existing github ID information. If they don't, then they should fill out [the onboarding form](https://hackmd.io/s/rkhHC2cFf) and we'll get them set up!

* there is now quite a bit of DCPPC content behind private github walls, and more will be created - start with [the consortium overview](https://github.com/dcppc/organize/blob/master/onboarding/consortium-overview.md#the-data-commons-pilot-phase-consortium).

* we also have google drive locations and protection where we can limit access to accounts that belong to Consortium members (including data stewards). We give membership to that through the onboarding form above, too.  So you can make specific folders or documents readable only by members of the Consortium - if you give access to 'dcppc-everyone@googlegroups.com' it *should* work.

* that having been said, we can certainly create a private repo. github links between issues in different repos fairly efficiently and cleanly. but if we don't need it, let's keep it simple and simply make sure links that should be access controlled are, indeed, access controlled.

Let me know if I can help!

**Comment by ctb** [comment]
(for @cmungall and others': we have a team `everyone` that should have access to almost everything on github.com/dcppc/.)

**Comment by bheavner** [comment]
Thanks @ctb - I suspect that the google drive access control will meet my current needs, so that addresses my reason for opening the issue. Are there other aspects to discuss, or should I close the issue?

**Comment by jmcmurry** [comment]
May I propose an alternative? Can we use the GitHub teams communication feature? These convos are private even when referring to a public repo. Integration with GitHub (issues, mentions etc) is seamless.

**Comment by bheavner** [comment]
I haven't used that feature before. Can you walk me through how would it work in a context like this, where we're basically having a public conversation via issue comments? How would I start a discussion and point to it from an issue comment, for example?

**Comment by avsmith** [comment]
@jmcmurry Educate me. Where is the teams feature and discussions?

**Comment by bheavner** [comment]
I've found some doc here: [https://help.github.com/articles/about-team-discussions/](https://help.github.com/articles/about-team-discussions/)

**Comment by bheavner** [comment]
Here's a first test of referencing a team discussion from a issue comment - [https://github.com/orgs/dcppc/teams/everyone/discussions/1](https://github.com/orgs/dcppc/teams/everyone/discussions/1).

**Comment by avsmith** [comment]
I'm unclear on how to get this link to work (and be on "The Team"). I get a 404 when clicking.

**Comment by bheavner** [comment]
But I hear that you already need to be onboarded to get to that link, so you may need to start here, @avsmith : [https://hackmd.io/s/rkhHC2cFf#](https://hackmd.io/s/rkhHC2cFf#)

**Comment by charlesreid1** [comment]
As an FYI, here are [instructions from Github](https://help.github.com/articles/creating-a-team-discussion/) on how to bring up team discussions (slightly better than the "about" page above). (The short version: go to your Settings page, then click Organizations, then click Teams. Picking the team should bring up the discussions page.)

Something to keep in mind (potentially confusing to users) is that this is not an _organization_ feature, it is a _team_ feature (`organizations > teams`), so a team discussion is only open to members of that team, not all members of an organization. 

@bheavner had a good first example that was a discussion for the "everyone" team.

**Comment by bheavner** [comment]
The team discussion feature satisfies our needs. Thanks for the help and discussion, all!
