### ISSUE TITLE
Access Denied on Some S3 Bucket Files

### ISSUE THREAD

**Issue by zflamig** [dcppc/data-stewards#23]
Using the assumed role and attempting to access some files I get access denied, for example:
s3://nih-nhlbi-datacommons/NWD156483.freeze5.v1.vcf.gz

But there are several other files in the vcf list for this project that also have the problem. I haven't checked everything yet.

If necessary I can try to provide a full list of files with this error in the future too.

**Comment by AlastairThomson** [comment]
My team is investigating - Can you provide a full list of files with issues?

Alastair NIH/NHLBI

**Comment by zflamig** [comment]
Thanks @AlastairThomson. I will get you that list by the end of the week.

Coming around to GTEx, we had similar problems with some of the RNASeq files. Noteably everything in https://github.com/dcppc/full-stacks/blob/master/gtex-rnaseq.tsv that doesn't have a data GUID assigned to it by us we were unable to access.

**Comment by zflamig** [comment]
Hi @AlastairThomson please see the following TSV files. Ones with missing filenames/Calcium GUIDs are files to which we did not have access.
https://github.com/dcppc/full-stacks/blob/master/topmed-vcf.tsv
https://github.com/dcppc/full-stacks/blob/master/topmed-vcfcsi.tsv
https://github.com/dcppc/full-stacks/blob/master/topmed-cram.tsv
https://github.com/dcppc/full-stacks/blob/master/topmed-crai.tsv

**Comment by dzakpasuns** [comment]
Hi Zac, 

Resolution: Objects listed in these TSV files (TOPMed and GTEx) are now tagged for cross-account access.
Please note: investigating these problems revealed some TOPMed samples do not have corresponding VCF and VCF_CSI files. Attached are listings of VCF and VCF_CSI objects that are in the s3://nih-nhlbi-datacommons bucket.

[topmed-vcf-CSI-object-list.txt](https://github.com/dcppc/data-stewards/files/2266690/topmed-vcf-CSI-object-list.txt)
[topmed-vcf-object-list.txt](https://github.com/dcppc/data-stewards/files/2266691/topmed-vcf-object-list.txt)

**Comment by zflamig** [comment]
Thanks! Works great now.
