### ISSUE TITLE
Register data steward APIs with smartAPI

### ISSUE THREAD

**Issue by cmungall** [dcppc/data-stewards#5]
See also: https://github.com/dcppc/apis/issues/6

http://smart-api.info/registry

Please note any issues here
- [ ] #1 Topmed (also here: https://github.com/dcppc/apis/issues/3)
- [ ] #2 MODs
     - [ ] GO enrichment in the cloud @mugitty 
- [ ] #3 GTEx

**Comment by jdepons** [comment]
The RGD API has been added and tagged with NIHdatacommons

**Comment by jmcherry** [comment]
This is in the works. I understand should be documented in swagger first

**Comment by jmcherry** [comment]
Forwarded to tech staff they’ll comment here.

**Comment by jdepons** [comment]
This may not be an issue for everybody, but it was for us.  

Our API currently uses Swagger 2.0.  The Smart API repository requires Open API 3.0.  I used the following library to do the conversion prior to registration.   https://www.npmjs.com/package/api-spec-converter

**Comment by cmpich** [comment]
ZFIN does not really have a published API at this point. We can make it a priority to generate it. What is the purpose of this? The Alliance has an API for retrieving the data types that are in the database. Obviously, this is only a subset of data from each MOD. APIs from the MODs I would presume would have more data. Should those APIs synchronized in any way? Should at least the names for the same attributes be the same?

**Comment by cmungall** [comment]
@jdepons - we have the same issue with the GO API. The framework we are using generates OpenAPI 2.0. It would be great if the smartAPI system could do the conversion centrally, cc @newgene

**Comment by cmungall** [comment]
@cmpich this is one of the DC milestones, you can read more at [1M.2.PRODUCT An API Registry for the definition and discovery of APIs](https://docs.google.com/document/d/1TnuaCkEPOfzhRCS1FHH0E3QS4O5gPV6NwH-W-kscIeQ/edit)

**Comment by newgene** [comment]
@cmungall Automated conversion from v2 to v3 is not always reliable. They are very useful, saving a lot of time, but still requires people to manually inspect it after the conversion and test it in a v3 editor to make sure everything is correct.

In our step-by-step user guide, we listed the several useful tools for v2-to-v3 conversion: http://smart-api.info/documentation .  I'm not aware of this "[api-spec-converter](https://www.npmjs.com/package/api-spec-converter)" tool mentioned by @jdepons. Will add it to our documentation in case others find useful.

**Comment by cmungall** [comment]
Ours is generated by a framework so manual patching is not really an 
option

**Comment by jnedzel** [comment]
GTEx is currently on Swagger 1.2.  We are working to upgrade to Swagger 2.0.  We hope to complete that by May 1st.  

Our Swagger documentation is automatically generated from our code.  This ensures that our documentation remains up to date.  Can someone please point me towards instructions for automating loading from Swagger 2.0 into Smart API?  Our API is under active development, so we must automate this.  Having to do this manually is a non-starter for us.

**Comment by cmungall** [comment]
We're in exactly the same position as @jnedzel

**Comment by newgene** [comment]
@cmungall @jnedzel we will try to add some limited support for swagger 2.0 in SmartAPI.
Ref: https://github.com/SmartAPI/smartAPI/issues/12

**Comment by jnedzel** [comment]
Will that be in time for the May 7th deliverable?

**Comment by newgene** [comment]
I cannot promise on that :-), but try out best.

**Comment by bheavner** [comment]
I see that this is tagged with TOPMed. Can you please help clarify what you’re seeking from us as data stewards? I’m not sure that the TOPMed data stewards are the right people for this issue - TOPMed does not provide any APIs.

We are aware of (but do not extensively use) the NIH Entrez Programming Utilities  - [https://www.ncbi.nlm.nih.gov/books/NBK25501/](https://www.ncbi.nlm.nih.gov/books/NBK25501/) which appear to be an API that can be used to programmatically interact with dbGaP data, but again, it is not a TOPMed-specific API.

**Comment by jnedzel** [comment]
GTEx has upgraded to Swagger 2.0 and registered its API.  We had to do part of this manually, so we have not yet integrated this into our build process.  Once SmartAPI provides an automated way to add/update APIs, we will then work on integrating this into our build process.  Until that happens, we will not be able to keep this information current.

**Comment by jnedzel** [comment]
@newgene I'm not sure that will work for us, due to our workflow.

We don't start by editing our YAML and generate code from the YAML.  Instead, we write our code, and during our build step, generate the YAML from our code.  So we don't have the YAML when we commit to GitHub.

I will confirm with our Swagger expert next week.

**Comment by newgene** [comment]
@jnedzel Even though YAML is auto-generated, I assume you will need to have that YAML output stored somewhere, and github (like your own repo) would be a natural place to have it. SmartAPI does not host any metadata. The registration step only records the URL of the metadata (can be hosted anywhere). And in practice, most of APIs have their metadata hosted in github.

If you want to fully automate your process, I'm sure you can trigger a "git commit" in the build process.

**Comment by jnedzel** [comment]
@newgene No, we don't ever store the YAML.  We don't have any need to store it in GitHub.

**Comment by jnedzel** [comment]
We do have a publicly accessible URL for our API metadata.  The YAML behind that URL is autogenerated from our code when we start our server.  But we are not archiving the YAML itself.  We have added a step in our build process in order to capture the YAML so that we can translate to Open API 3.  We have then manually registered to SmartAPI.

We use the YAML to drive the Swagger UI.  It is like Javadoc for us.

**Comment by newgene** [comment]
Got it. As long as you register that URL once, we can run a daily update to keep the metadata in-sync. You don't need to update manually every time you change something.

**Comment by jnedzel** [comment]
The GTEx API has been added.  We don't have this process automated yet.

**Comment by gabinkley** [comment]
SGD has just registered their API.  See ttp://smart-api.info/ui/c6e46d8e4d5a1297adb38237edf38f08
