### ISSUE TITLE
make this repo public?

### ISSUE THREAD

**Issue by cmungall** [dcppc/data-stewards#8]
Any objections to making this repo public?

If there are objections then I would like to make sure that all the alliance technical members have read access. I can coordinate this, if someone gives me the power to add new people (I assume to the [everyone](https://github.com/orgs/dcppc/teams/everyone/members) team).

**Comment by cmungall** [comment]
ah OK, I started adding people and then we ran out of 'seats'. I believe this is one of the limitations they have on private repos, unless you upgrade the plan. Given there seems to be agreement to make this public and there is nothing that seems private in the tickets so far, I'm wielding my new-found powers to make this repo public.

**Comment by ctb** [comment]
please let me know how many more seats we need! I can continue upgrading
to meet the need.

**Comment by ctb** [comment]
(which will be useful beyond this repo)
